/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
#include "../../../../../../../../Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h"
/* Header for class com_ndkdev_utils_NDKUtilsJ */

#ifndef _Included_com_ndkdev_utils_NDKUtilsJ
#define _Included_com_ndkdev_utils_NDKUtilsJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndkdev_utils_NDKUtilsJ
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndkdev_utils_NDKUtilsJ_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
